{% set version = "0.20.4" %}
{% set name = "scikit-learn" %}
{% set variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/scikit-learn/scikit-learn/archive/{{ version }}.tar.gz
  sha256: cadeefa9a824671bdcad790a075efbaa0d5a00458c43c9b4ce7110b129df7b10

build:
  number: 0
  # We lack scipy on Windows, and therefore can't build numpy there either currently.
  skip: true  # [win]
  features:
    - blas_{{ variant }}
  script: python -m pip install --no-deps --ignore-installed .  --verbose

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas
    - numpy
    - scipy
    - pytest
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  requires:
    - pytest
  imports:
    - sklearn
  commands:
    - OPENBLAS_NUM_THREADS=1 pytest --verbose --pyargs sklearn

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
    - jnothman
